In [4]:
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib

In [2]:
def Cov(x, y):
    return np.mean(x*y) - np.mean(x)*np.mean(y)

def Var(x):
    return np.sum((x - np.mean(x))**2)

In [47]:
D = np.array([[1,3], [3,6], [6,5],[8,7]])

In [59]:
x = D[:, 0]
y = D[:, 1]
X = np.array([[1,x[0]], [1, x[1]], [1, x[2]], [1, x[3]]])
print(X)
print('--------')
print(X.T)

[[1 1]
 [1 3]
 [1 6]
 [1 8]]
--------
[[1 1 1 1]
 [1 3 6 8]]


In [71]:
H = np.dot(X.T, X)

In [72]:
H_inv = np.array([[110, -18], [-18, 4]]) / (4*110 - 18*18)

In [92]:
S = X.T @  y.T
S

array([ 21, 107])

In [93]:
w = H_inv @ S
w

array([3.31034483, 0.43103448])

In [94]:
p = np.polyfit(x, y, 1)
p

array([0.43103448, 3.31034483])

In [26]:
X = np.array([[1,1], [1, 3], [1,6], [1, 8]])
Y = np.array([3, 6, 5, 7])
print(X, Y)
X.T @ X

[[1 1]
 [1 3]
 [1 6]
 [1 8]] [3 6 5 7]


array([[  4,  18],
       [ 18, 110]])

In [28]:
W = np.linalg.inv(X.T@X)@X.T@Y
W

array([3.31034483, 0.43103448])